### ISSUE TITLE
Error: Can't resolve './flickity' in node_modules\flickity-fullscreen (webpack)

### ISSUE THREAD

**Issue by wc-matteo** [metafizzy/flickity-fullscreen#1]
```js
import Flickity from 'flickity-fullscreen'
new Flickity('.slides', {
  fullscreen: true
})
```

**Comment by desandro** [comment]
Thanks for reporting this issue. This bug will be fixed in the next release, coming in 1 week.

**Comment by LehtinenRiku** [comment]
Is this somehow related to this? https://discourse.roots.io/t/relative-module-was-not-found-flickity-slider/12025/2

I got this error:
This relative module was not found:
* ./flickity in ./node_modules/flickity-fullscreen/fullscreen.js

**Comment by desandro** [comment]
v1.0.1 has been released with fix added. Closing!
