### ISSUE TITLE
Vanilla javascript fullscreenChange event only passes one argument to the handler

### ISSUE THREAD

**Issue by gonssal** [metafizzy/flickity-fullscreen#12]
It seems that the `fullscreenChange` event handler, when used in vanilla JS, only gets a single `isFullscreen` argument instead of the two documented in the readme. So I think it should be:

```javascript
flkty.on( 'fullscreenChange', function( isFullscreen ) {...} );
```

Codepen: https://codepen.io/anon/pen/dKWaLy

Not sure about the jQuery namespaced event, but I think it's the same.

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. Actually, it's a bit confusing. Some Flickity events do have an `event` argument, which matches the jQuery arguments. But others, like `fullscreenChange` do not. [It's documented as such](https://flickity.metafizzy.co/events.html#fullscreenchange):

``` js
// jQuery
$carousel.on( 'fullscreenChange.flickity', function( event, isFullscreen ) {...});

// vanilla JS
flkty.on( 'fullscreenChange', function( isFullscreen ) {...});
```

**Comment by gonssal** [comment]
I used this project's README as documentation, and it says:

```javascript
flkty.on( 'fullscreenChange', function( event, isFullscreen ) {...} );
```

So I guess there's the issue. Thanks for answering.
