### ISSUE TITLE
Add [type=button] to the [flickity-fullscreen-button]

### ISSUE THREAD

**Issue by jstnrs** [metafizzy/flickity-fullscreen#18]
When the slider and thus the button to activate is within a form element, the button now submits the form. When adding `type="button"` to the (open and close) buttons, this would not be the case.

**Comment by jstnrs** [comment]
I've opened a Pull request here with a fix, which is also used in the Flickity sources (https://github.com/metafizzy/flickity/blob/master/js/prev-next-button.js#L58): https://github.com/metafizzy/flickity-fullscreen/pull/19

**Comment by desandro** [comment]
Ah! Thanks for catching this and submitting a PR. The PR has been Merged! This will be a part of the next release 🌈🐻

**Comment by desandro** [comment]
Released in [flickity-fullscreen v1.1.1](https://github.com/metafizzy/flickity-fullscreen/releases/tag/v1.1.1)
