### ISSUE TITLE
Google Closure Compiler fails with fullscreen.js

### ISSUE THREAD

**Issue by X-Fate** [metafizzy/flickity-fullscreen#2]
Hi there,

first, thanks for your great work with fullscreen.js and Flickity v2!
I want to report an issue with the Google Closure Compiler:

Google closure compilation has errors: [JSC_TRAILING_COMMA. Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option. at /js/vendor/flickity/fullscreen.js line 15 : 33, JSC_TRAILING_COMMA. Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option. at /js/vendor/flickity/fullscreen.js line 154 : 66]

See:
```
var pathDirections = {
  view: 'M15,20,7,28h5v4H0V20H4v5l8-8Zm5-5,8-8v5h4V0H20V4h5l-8,8Z',
  exit: 'M32,3l-7,7h5v4H18V2h4V7l7-7ZM3,32l7-7v5h4V18H2v4H7L0,29Z',
};
```

The trailing comma should be removed.
Thanks in advance.

Cheers,
X-Fate

**Comment by desandro** [comment]
Thanks for reporting this issue. Flickity v2 does not support IE8. I recommend you _set the appropriate language_in option_
