### ISSUE TITLE
Slides mounted on top of each other / imagesLoaded not working 

### ISSUE THREAD

**Issue by fenoco-fauna** [metafizzy/flickity-fullscreen#27]
Hi, I'm having a strange issue. I have my slider set up using imagesLoaded but when I load the page slides are mounted on top of each other, and only rearrange themselves if I resize the window. I've checked and tried everything that I can think of. Here's an example (it's the slider in the bottom of the page): http://www.fundaciongasco.cl/noticia/gran-convocatoria-en-encuentro-con-benito-rojo/

Thanks in advance for any feedback,

**Comment by mattneal-stafflink** [comment]
I know this is a long shot, but I'm having the exact same issue and I can't figure out what I'm doing wrong. Are you able to provide some insight into how you fixed it or what you were doing wrong @fenoco-fauna ?
